### ISSUE TITLE
Deviceclass configmap wrong parameters

### ISSUE THREAD

**Issue by DebakelOrakel** [projectsyn/component-topolvm#3]
TopoLVM configmap `topolvm-lvmd0` has wrong parameter names:

currently is:
```
deviceClasses:
    - name: ssd
      volumegroup: myvg1
      default: true
      sparegb: 10
```

should be:
```
deviceClasses:
    - name: ssd
      volume-group: myvg1
      default: true
      spare-gb: 10
```
